import csv
import json

base_gen = "Generate a retro-clean 2D illustration with clean flat outlines and flat soft colors in an illustrated lifestyle handbook style. "
base_ref = "Using the provided reference image(s) when available, generate a retro-clean 2D illustration with clean flat outlines and flat soft colors in an illustrated lifestyle handbook style. "
exclusion = "Keep the same character identity and wardrobe family when reference continuity exists. No readable text. Avoid photorealistic rendering, avoid busy clutter, avoid direct-to-camera speech."
char_desc = "An older Japanese woman (60s, silver-gray hair, visible wrinkles, mature posture) "

def make_prompt(base, middle):
    return base + middle + " " + exclusion

data = [
    (1, "SG01", "host_anchor", "host", "", "reference_first_locked",
     make_prompt(base_ref, char_desc + "stands in a warm domestic Japanese kitchen, looking slightly tired. Warm earth tones.")),
    (2, "SG01", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "stands in front of a domestic kitchen stove, lightly wiping sweat from her forehead with a towel or handkerchief. Warm earth tones.")),
    (3, "SG01", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Clean symbolic scene of a Japanese kitchen interior enveloped in a faint warm-color wash to represent trapped heat and humidity. No human subject.")),
    (4, "SG01", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "stands at the kitchen counter chopping vegetables in her everyday routine, comfortable and familiar.")),
    (5, "SG01", "host_anchor", "host", "", "reference_first_locked",
     make_prompt(base_ref, char_desc + "pauses her cooking, looking thoughtfully and calmly at her kitchen space, expressing a reassuring sense of realization.")),
    (6, "SG01", "host_anchor", "host", "", "reference_first_locked",
     make_prompt(base_ref, char_desc + "smiles warmly, gesturing gently with one hand in a welcoming, reassuring manner, inviting the viewer to review the kitchen.")),
    (7, "SG01", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Four simple, clear icons arranged neatly: a refrigerator, an exhaust fan, a gas stove, and a clean sponge, representing the four safety points. Checklist-friendly layout.")),
    (8, "SG01", "host_anchor", "host", "", "reference_first_locked",
     make_prompt(base_ref, char_desc + "smiles gently, nodding reassuringly, conveying that small steps are enough.")),
    
    (9, "SG02", "environment_bridge", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A calm, wide shot of a neatly kept Japanese kitchen filled with warm summer sunlight streaming through the window.")),
    (10, "SG02", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, "An older Japanese man (70s, gray hair, wrinkles) resting in an indoor chair, looking a bit exhausted from indoor heat.")),
    (11, "SG02", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Close-up of a domestic gas stove with steam rising from a pot, showing how heat builds up in the kitchen.")),
    (12, "SG02", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Clean illustration of a kitchen with a small window and faint warm-colored air trapped inside, symbolizing poor ventilation.")),
    (13, "SG02", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "drinking a glass of water, looking dry and slightly unaware of the heat.")),
    (14, "SG02", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "leaning lightly against the kitchen counter, showing a subtle accumulation of fatigue. Calm and observational.")),
    (15, "SG02", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Close-up of a kitchen sponge and dishcloth with small graphic germ symbols symbolizing bacteria growth during summer wetness.")),
    (16, "SG02", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Close-up of a kitchen stove burner area, clean but highlighting it as a focus point for safety.")),
    (17, "SG02", "host_anchor", "host", "", "reference_first_locked",
     make_prompt(base_ref, char_desc + "smiles gently, holding one hand up softly in a 'don't worry' reassuring gesture.")),

    (18, "SG03", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A clean closed domestic Japanese refrigerator in a warm, inviting kitchen corner.")),
    (19, "SG03", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "The inside of a refrigerator completely packed tightly with many food containers and groceries, leaving no empty space.")),
    (20, "SG03", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Cutaway of a packed refrigerator showing cool blue air-flow arrows being blocked by too much food. Abstract and clear.")),
    (21, "SG03", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A thermometer icon showing the temperature rising slightly inside the packed refrigerator, with warm colors. Symbolic explanation.")),
    (22, "SG03", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, "The inside of a refrigerator that is nicely arranged and only 70 percent full, with plenty of visible empty space.")),
    (23, "SG03", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "looking peacefully at the well-spaced items inside her open refrigerator.")),
    (24, "SG03", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Close-up of raw meat and fish securely wrapped in plastic wrap and placed neatly on a tray.")),
    (25, "SG03", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "The securely wrapped meat and fish placed cleanly in the lower chilled section of the refrigerator.")),
    (26, "SG03", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "returning from grocery shopping with an eco-bag, promptly placing items into the fridge.")),
    (27, "SG03", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Fresh food items sitting idly on a warm kitchen counter with summer sunlight warming them, showing what to avoid.")),
    (28, "SG03", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Clean, neatly stacked Tupperware containers of leftover side dishes placed safely inside the refrigerator.")),
    (29, "SG03", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Close-up of a food package showing a printed date, emphasizing the action of checking the expiration date. Clean and clear.")),
    (30, "SG03", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "calmly tossing an expired food item into the kitchen trash bin without panic.")),
    (31, "SG03", "host_anchor", "host", "", "reference_first_locked",
     make_prompt(base_ref, char_desc + "smiling gently, holding one hand to her chest, expressing 'take it slow, one step at a time'.")),

    (32, "SG04", "environment_bridge", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A wall-mounted kitchen exhaust fan in a clean Japanese apartment kitchen.")),
    (33, "SG04", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Close-up of an older weathered hand pressing the power switch for the kitchen exhaust fan.")),
    (34, "SG04", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Visual representation of steam and hot air being effectively drawn out of the kitchen through the exhaust fan. Symbolic.")),
    (35, "SG04", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Warm outside summer air entering through a ventilation window, represented by a gentle warm sweep of color.")),
    (36, "SG04", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Close-up of an air conditioner mounted on the wall politely blowing cool, refreshing blue air into the room.")),
    (37, "SG04", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "cooking comfortably at the stove while cool air flows around her. Calm and protected.")),
    (38, "SG04", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Split comparison: an electricity bill icon on one side, and a healthy heart icon on the other, showing balance. Symbolic.")),
    (39, "SG04", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A clean microwave oven sitting conveniently on a tidy kitchen counter.")),
    (40, "SG04", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "relaxing on a dining chair, wiping sweat lightly, while the microwave operates in the background.")),
    (41, "SG04", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A plate of easily prepared side dishes on the table, indicating a meal made with minimal stove time.")),
    (42, "SG04", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A refreshing glass of cool water and a cup of cold tea on the kitchen counter.")),
    (43, "SG04", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "consciously drinking a cup of water during her cooking breaks.")),
    (44, "SG04", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "sitting on a small stool in the kitchen, taking a short, calm rest from cooking.")),
    (45, "SG04", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "slowly rubbing her temple with a tired expression, portraying lingering summer fatigue.")),
    (46, "SG04", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "calmly walking toward a neighborhood clinic on a sunny day. Seen from behind or wide angle.")),

    (47, "SG05", "environment_bridge", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A calm setup of a domestic Japanese gas stove with pans ready to cook.")),
    (48, "SG05", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "looking down and touching the wide sleeves of her casual indoor clothing.")),
    (49, "SG05", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Minimal symbolic alert icon of a clothing sleeve dipping dangerously close to a stove flame. Focus on safety caution.")),
    (50, "SG05", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Textbook safety illustration of how wide sleeves catch fire from unseen blue flames. Educational clarity.")),
    (51, "SG05", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "squinting slightly, finding it hard to see the pale blue gas flame on the stove.")),
    (52, "SG05", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Close-up of a wide, loose chemical-fiber sleeve dangling downwards.")),
    (53, "SG05", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "rolling up her sleeves neatly into a compact form before starting to cook.")),
    (54, "SG05", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A clean flame-retardant safety apron hanging neatly on a hook in the kitchen.")),
    (55, "SG05", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "turning the stove knob off first before reaching out for a seasoning bottle deep in the shelf.")),
    (56, "SG05", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Close-up of an older weathered hand pressing the stove off button.")),
    (57, "SG05", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Abstract instructional diagram of a person stopping in place, not running. Stop-drop-roll step 1.")),
    (58, "SG05", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Abstract instructional diagram of a person rolling on the floor to extinguish flames. Hand-drawn educational style.")),
    (59, "SG05", "host_anchor", "host", "", "reference_first_locked",
     make_prompt(base_ref, char_desc + "giving a gentle nod of understanding, showing calm preparedness.")),
    (60, "SG05", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Close-up of a modern gas stove featuring a circular automatic shut-off safety sensor in the center burner.")),
    (61, "SG05", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Clean flat surface of a modern IH induction cooking heater in a neat kitchen.")),

    (62, "SG06", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A pair of clean, dry kitchen sponges and a neatly folded dishcloth. Practical home objects.")),
    (63, "SG06", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A wet sponge placed inside a small graphic outline representing warm, humid summer conditions.")),
    (64, "SG06", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A sponge surrounded by subtle visual cues of moisture, warmth, and tiny food scraps, creating a bacteria environment.")),
    (65, "SG06", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "thoroughly wringing out a kitchen sponge to remove all the water.")),
    (66, "SG06", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A clean sponge hung vertically from an airy rack to dry in a well-ventilated spot.")),
    (67, "SG06", "Everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A damp dishcloth left crumpled in a messy pile on the sink, showing what to avoid.")),
    (68, "SG06", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "carefully pouring boiling water over a sponge in the sink for disinfection.")),
    (69, "SG06", "host_anchor", "host", "", "reference_first_locked",
     make_prompt(base_ref, char_desc + "smiling gently, waving one hand softly left and right in a 'no need to be perfect' gesture.")),
    (70, "SG06", "object_focus", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A clean roll of disposable kitchen paper towels sitting on a neat holder on the counter.")),

    (71, "SG07", "host_anchor", "host", "", "reference_first_locked",
     make_prompt(base_ref, char_desc + "nodding and smiling mildly, reassuring the viewer that reviewing the points was good.")),
    (72, "SG07", "process_metaphor", "no_host", "", "generate_locked",
     make_prompt(base_gen, "Four clean icons returning together: a refrigerator, an AC unit, a stove, and a sponge. Summary layout.")),
    (73, "SG07", "environment_bridge", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A wide, safe, clean summer kitchen, softly illuminated and organized with small improvements.")),
    (74, "SG07", "everyday_example", "no_host", "", "generate_locked",
     make_prompt(base_gen, char_desc + "looking slightly fatigued but picking up a phone to comfortably consult her family doctor.")),
    (75, "SG07", "host_anchor", "host", "", "reference_first_locked",
     make_prompt(base_ref, char_desc + "smiling, demonstrating a relaxed, 'slow and steady' pacing to life.")),
    (76, "SG07", "host_anchor", "host", "", "reference_first_locked",
     make_prompt(base_ref, char_desc + "offering a gentle concluding smile, looking warm and trustworthy.")),
    (77, "SG07", "environment_bridge", "no_host", "", "generate_locked",
     make_prompt(base_gen, "A peaceful view of a bright blue summer sky and green leaves outside the kitchen window.")),
    (78, "SG07", "host_anchor", "host", "", "reference_first_locked",
     make_prompt(base_ref, char_desc + "bowing slightly and gracefully, thanking the viewer for watching. Polite wrap-up.")),
]

csv_file = "07_image_prompt_table.csv"
fieldnames = ["unit_index", "scene_group_id", "scene_archetype", "host_usage", "visible_text_policy", "visible_text_exact", "prompt_mode", "prompt_img_nano"]

with open(csv_file, mode="w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for row in data:
        writer.writerow({
            "unit_index": row[0],
            "scene_group_id": row[1],
            "scene_archetype": row[2].lower(),
            "host_usage": row[3],
            "visible_text_policy": "exact_visible_text" if row[4] else "no_readable_text",
            "visible_text_exact": row[4],
            "prompt_mode": row[5],
            "prompt_img_nano": row[6]
        })
print(f"Generated {csv_file} successfully.")
